repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]

- repo: https://github.com/psf/black
  rev: 21.8b0
  hooks:
  - id: black
    args:
      - --line-length=120
      - --include='\.pyi?$'
      - --exclude="""\.git |
        \.__pycache__ |
        \.tox |
        \.venv |
        _build |
        build |
        dist |
        doc"""


- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-typing-imports==1.1.0]
    args:
      - "--max-line-length=120"
      - "--max-complexity=18"
      - "--select=B,C,E,F,W,T4,B9"
      - "--ignore=C901,E203,E501,E731,W503,F401,F403,F405,F841"
